# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc458a0a7da968a802cee67add953d8748c2ea01ec0e525950f5fa4ad445c2bfb21167468f5ab79fe8f34143eb15ee0dcb8ce544f66ed2b1ba9b3cbdbe1e8faf

test:
  secret_key_base: 03a1a7d5e4f77a54e22af854f715721e7c2981d575315b376f602dae46a77b745fdba30135029cc7a3d822073ec581bf894c11324d4fe1d4323d19868d9f99ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
